# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jy6hC8rEzwjIC1MhMMWldjzxP6z3AnF8
"""

# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
bike_data = pd.read_csv("/content/dc_bike_share.csv")

# Display the first few rows of the dataset
print(bike_data.head())

# Check for missing values
print(bike_data.isnull().sum())

# Perform descriptive statistics
print(bike_data.describe())

# Explore the distribution of categorical variables
print(bike_data['season'].value_counts())
print(bike_data['holiday'].value_counts())
print(bike_data['weekday'].value_counts())

sns.histplot(bike_data['temp'], kde=True)
plt.title('Temperature Distribution')
plt.xlabel('Temperature')
plt.ylabel('Frequency')
plt.show()

sns.histplot(bike_data['hum'], kde=True)
plt.title('Humidity Distribution')
plt.xlabel('Humidity')
plt.ylabel('Frequency')
plt.show()

sns.histplot(bike_data['windspeed'], kde=True)
plt.title('Windspeed Distribution')
plt.xlabel('Windspeed')
plt.ylabel('Frequency')
plt.show()

# Explore bike usage with different factors
plt.figure(figsize=(10, 6))
sns.boxplot(x='season', y='count', data=bike_data)
plt.title('Bike Usage by Season')
plt.xlabel('Season')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='holiday', y='count', data=bike_data)
plt.title('Bike Usage on Holidays')
plt.xlabel('Holiday')
plt.ylabel('Count')
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(x='weekday', y='count', data=bike_data)
plt.title('Bike Usage by Weekday')
plt.xlabel('Weekday')
plt.ylabel('Count')
plt.show()

# Plot time series data
plt.figure(figsize=(14, 6))
sns.lineplot(x='dteday', y='count', data=bike_data)
plt.title('Bike Usage Over Time')
plt.xlabel('Date')
plt.ylabel('Count')
plt.xticks(rotation=45)
plt.show()

# Statistical Analysis
correlation_matrix = bike_data.corr()
print(correlation_matrix)